<div class="row">
	<div class="col-sm-9"><h2>Listado de tareas</h2></div>
	<div class="col-sm-3">
		<a href="<?php echo APP_URL."tareas/agregar"; ?>">
	 		<button type="button" class="btn btn-primary add">
	 			<span class="glyphicon glyphicon-plus"></span> Tarea
	 		</button>
	 	</a>
	 	<a href="<?php echo APP_URL."categorias/agregar"; ?>">
	 		<button type="button" class="btn btn-primary add">
	 			<span class="glyphicon glyphicon-plus"></span> Categoria
	 		</button>
	 	</a>
	</div>

	
</div>
<div class="row">
	<div class="col-sm-12">
		<ul class="nav nav-tabs">

		   <?php
		  	$i = 0;
		  	$categoriasId= array();
			foreach ($this->categorias as $categoria): 
				if ($i==0): ?>
					<li class="active"><a data-toggle="tab" href="#<?php echo $categoria["nombre"]; ?>"><?php echo $categoria["nombre"]; ?></a></li>
			<?php else: ?>
				 <li><a data-toggle="tab" href="#<?php echo $categoria["nombre"]; ?>"><?php echo $categoria["nombre"]; ?></a></li>
			<?php 
				endif; 
				$i++;
				$categoriaId["id"][] = $categoria["id"];
				$categoriaId["nombre"][] = $categoria["nombre"];
			endforeach;
			 ?>
		</ul>
	</div>
</div>

<div class="tab-content">
<?php
	for ($j=0; $j < $i ; $j++):
		if ($j==0): ?>
			<div id="<?php echo $categoriaId["nombre"][$j]; ?>" class="tab-pane fade in active">
		<?php else: ?>
			<div id="<?php echo $categoriaId["nombre"][$j]; ?>" class="tab-pane fade">
		<?php endif; ?>
		<br>
	
		<?php

		if (empty($this->tareas)):
				echo "<h3>Sin tareas</h3>";
		else:
		?>			
		<table class="table">
			<tr>
				<th>ID</th>
				<th>Nombre</th>
				<th>Fecha</th>
				<th>Prioridad</th>
				<th>Acción</th>
			</tr>
		<?php 

			foreach ($this->tareas as $tarea): 
				if ($tarea["categorias"]["id"]== $categoriaId["id"][$j]):
		?>
			<tr>
				<td><?php echo $tarea["tareas"]["id"]; ?></td>
				<td><?php 
					if($tarea["tareas"]["status"]==0):
						echo "<s>".$tarea["tareas"]["nombre"]."</s>"; 	
					else:
						echo $tarea["tareas"]["nombre"];
					endif;
					?>
				</td>
				<td><?php
					$date = date_create($tarea["tareas"]["fecha"]);
					echo date_format($date, 'd/m/Y');
					?>
				</td>
				<td><?php 
					if ($tarea["tareas"]["prioridad"]<=3):
						echo '<span class="label label-success">Baja&nbsp;&nbsp;&nbsp;</span>';
					elseif($tarea["tareas"]["prioridad"]<=6):
						echo '<span class="label label-warning">Media</span>';	
					elseif($tarea["tareas"]["prioridad"]<=10):
						echo '<span class="label label-danger">Alta&nbsp;&nbsp;&nbsp;</span>';
					endif;
					?>
				</td>
				<td><a href="tareas/edit/<?php echo $tarea["tareas"]["id"]; ?>"><span class="glyphicon glyphicon-edit"></a>
			<?php 	if ($tarea["tareas"]["status"]==0): ?>
						<a href="tareas/status/on/<?php echo $tarea["tareas"]["id"]; ?>">
							<span class="glyphicon glyphicon-remove"></span>
						</a>
					<?php else: ?>
						<a href="tareas/status/off/<?php echo $tarea["tareas"]["id"]; ?>">
							<span class="glyphicon glyphicon-ok"></span>
						</a>
			<?php 	endif; ?>
						<a href="tareas/delete/<?php echo $tarea["tareas"]["id"]; ?>">
							<span class="glyphicon glyphicon-trash"></span>
						</a>
					</td>
			</tr>
		<?php 
		endif;
		endforeach; 
		
		?>
		</table>
	<?php endif; ?>
	</div>
<?php endfor; ?>
</div>